name: test2


on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' # All History


      - name: test (Composite Action)
        uses: ./composite_actions/test


